name: Notify Project Desc Change
on:
  push:
    branches:
      - main
    paths:
      - 'project-description.md'
  create:
    paths:
      - 'project-description.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Gundalai-Batkhuu/my-portfolio/dispatches \
            -d '{"event_type":"sync_markdown"}'